 version: 0.2

 phases:
    build:
       commands:
          - echo entered into build phase...
          - mvn clean package
    post_build:
       commands:
          - echo entered into build phase...
 artifacts:
    files:
       - target/CodeBuildApp.jar
    discard-paths: yes

          
       